apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bp3oedurw-python 
  janus-idp.io/tekton: bp3oedurw-python
  backstage.io/kubernetes-id: bp3oedurw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bp3oedurw-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml