apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bp3oedurw-python
  janus-idp.io/tekton: bp3oedurw-python
  backstage.io/kubernetes-id: bp3oedurw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bp3oedurw-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
