apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bp3oedurw-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bp3oedurw-python 
  name: bp3oedurw-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bp3oedurw-python 
